equinor/fmu-sumo-sim2sumo

- src/fmu/sumo/sim2sumo/_special_treatments.py
- src/fmu/sumo/sim2sumo/sim2sumo.py
> Fix rft welletc

- src/fmu/sumo/sim2sumo/sim2sumo.py
Pass `config_path` to `sumo_upload`. `sumo_upload` will attempt to upload parameters.txt which needs the config to produce metadata using `fmu-dataio`. This operation is currently failing if the asset has their global variables somewhere other than `fmuconfig/output/global_variables.yml`. This PR is dependent on a PR in the uploader: https://github.com/equinor/fmu-sumo-uploader/pull/14
> Add conf path

- src/fmu/sumo/sim2sumo/sim2sumo.py
- tests/test_functions.py
Fix  lack of export with fmudataio when running Drogon. 
When creating this branch the following stderror could be observed when running drogon in bleeding:
`Error reading summary instance, returning empty dataframe
Trace: [Errno 2] No such file or directory: 'ix/model/.RFT',
No results produced
Error reading summary instance, returning empty dataframe
Trace: [Errno 2] No such file or directory: 'opm/model/.RFT',
No results produced
Error reading summary instance, returning empty dataframe
Trace: [Errno 2] No such file or directory: 'pflotran/model.RFT',
No results produced
WARNING:fmu.sumo.uploader.scripts.sumo_upload:Problem related to Sumo upload: case metadata not found: share/metadata/fmu_case.yml <class 'OSError'>
WARNING:fmu.sumo.uploader.scripts.sumo_upload:Problem related to Sumo …
> bugfix:find_datafiles

- .github/workflows/build_docs.yaml
- .github/workflows/run_tests.yaml
This should remove these warnings:
"Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: Azure/login@v1, actions/checkout@v3, actions/setup-python@v3."
The tests that fail now is not related to this PR.
> Update github actions to move away from node 16

- src/fmu/sumo/sim2sumo/common.py
Also solves an issue where everything fails if the `sim2sumo` section is missing from the config.
> Remove redundant logging

- src/fmu/sumo/sim2sumo/_special_treatments.py
- src/fmu/sumo/sim2sumo/tables.py
Remove suffix from filepath before calling `res2df.ResdataFiles`.
`ResdataFiles` warns if file does not have `.DATA` suffix, but still works if file does not have it.
So res2df seems to work on files if they don't have suffix. However, if there **is** a suffix that is **not** `.DATA` then it will fail since res2df only ignores `.DATA` specifically.
So if we remove the suffix before passing filepath to res2df it should work (given that the path points to a valid file), without needing the correct suffix.
This solves an issue with files from "Intersect" with suffix `.afi`
> Remove suffix before calling res2df

- .github/workflows/run_tests.yaml
- src/fmu/sumo/sim2sumo/common.py
- src/fmu/sumo/sim2sumo/main.py
- tests/test_functions.py
Tests will fail until https://github.com/equinor/fmu-sumo-uploader/pull/89 is merged.
> Pass config_path to uploader

- .github/workflows/run_tests.yaml
- src/fmu/sumo/sim2sumo/_special_treatments.py
- src/fmu/sumo/sim2sumo/common.py
- src/fmu/sumo/sim2sumo/grid3d.py
- src/fmu/sumo/sim2sumo/main.py
- src/fmu/sumo/sim2sumo/tables.py
- tests/conftest.py
- tests/data/reek/realization-0/iter-0/fmuconfig/output/global_variables.yml
- tests/data/reek/realization-0/iter-0/fmuconfig/output/global_variables_w_eclpath.yml
- tests/data/reek/realization-0/iter-0/fmuconfig/output/global_variables_w_eclpath_and_extras.yml
- tests/data/reek/realization-0/iter-0/share/results/tables/.2_r001_reek--rft.csv.yml
- tests/data/reek/realization-0/iter-0/share/results/tables/.2_r001_reek--wellconnstatus.csv.yml
- tests/data/reek/realization-1/iter-0/fmuconfig/output/global_variables.yml
- tests/data/reek/realization-1/iter-0/fmuconfig/output/global_variables_w_eclpath.yml
- tests/data/reek/realization-1/iter-0/fmuconfig/output/global_variables_w_eclpath_and_extras.yml
- tests/test_functions.py
- tests/test_w_drogon.py
- tests/test_with_ert.py
Related to #78 #87 
* Remove or simplify multiple functions
* Remove unused functions
> Refactoring

- src/fmu/sumo/sim2sumo/main.py
`fmu-dataio` requires certain ERT variables to be set in order to create metadata correctly.
Add check to see if they are set, if not print error and exit.
> Require certain ERT env variables before running

- src/fmu/sumo/sim2sumo/common.py
- src/fmu/sumo/sim2sumo/tables.py
- tests/test_functions.py
Currently sim2sumo finds all paths to datafiles with valid filetypes `.DATA`, `.afi` and `.in`. However only the stem name are used as table name (and not the subfolders). Hence if two datafiles has same stem the random first one will be chosen, not taking into account the _seedpoint_ (or `datafile:`) given in the config file. ~This does not fix that, but it does at least prioritize the `.DATA` file over `.afi` and `.afi` over `.in` making the results consistent over an ensemble.~ This tries to fix that 😅
> Fix datafiles

- docs/sim2sumo.rst
- src/fmu/sumo/sim2sumo/_special_treatments.py
- src/fmu/sumo/sim2sumo/common.py
- src/fmu/sumo/sim2sumo/grid3d.py
- src/fmu/sumo/sim2sumo/hook_implementations/jobs.py
- src/fmu/sumo/sim2sumo/main.py
- src/fmu/sumo/sim2sumo/tables.py
- tests/conftest.py
- tests/test_functions.py
- tests/test_with_ert.py
* Reduce some flexibility in regards to config. `datafile` now has to be a list where each element is either a filepath, folderpath or a dictionary with key=filepath/folderpath and value=list of filetypes.
* Also, `datatypes` has to be a list
* Remove verbose logging
* Remove `--datatype` and `--datafile` arguments from main function. These were only for test use.
* Validate `datafile` in config is a list and dictionary elements have exactly 1 key.
* Refactor parsing of `datafile` from config
* Do not crash if failing to `create_config_dict`. Instead, log error and return.
* Formatting
Possibly related to #87
> More refactoring

- .github/workflows/run_tests.yaml
- pyproject.toml
`fmu-sumo-uploader` no longer supports Python 3.8 https://github.com/equinor/fmu-sumo-uploader/pull/109
Remove support from sim2sumo as well.
> chore: Drop support for Python 3.8

- src/fmu/sumo/sim2sumo/_special_treatments.py
Closes #120 
Default column type to `string`. Only do `float32` if certain column has numbers.
> fix: Default arrow conversion to string type

- src/fmu/sumo/sim2sumo/grid3d.py
- tests/test_functions.py
- tests/test_w_drogon.py
- tests/test_with_ert.py
Closes #106 
* Separate methods for creating metadata for `grids` and `grid properties`
* Add `"geometry": grid` to the `ExportData` arguments when creating metadata for `grid properties`
* This involves exporting the grid and its metadata to disk (dataio currently does not support "linking" geometry to a grid that is not on disk) The created files are deleted after upload to Sumo is done
> Link grid properties to a geometry

- src/fmu/sumo/sim2sumo/tables.py
- tests/test_functions.py
- tests/test_with_ert.py
Closes https://github.com/equinor/sumo-fmu-aggregation-service/issues/330
For summary tables with a defined table index:
* Split the table into chunks of up to 500 columns each and upload them with metadata `_sumo.hidden: true`
* The original table is also uploaded
> feat: Split tables before upload

- src/fmu/sumo/sim2sumo/common.py
- tests/test_functions.py
Closes #118 
The `options` parameter is no longer documented and if not specified it simply sets `arrow: True`
Removed the support for `options` completely and replaced the relevant parsing with hardcoded `arrow: True`
> feat: remove options from config

- .github/workflows/run_tests.yaml
- pyproject.toml
Closes #117 
Sim2sumo is definitely dependent on sumo-uploader, but for historical purposes was not added as an installation dependency.
It still works for Komodo because the uploader is included in Komodo separately. (Note that in Komodo-releases Sumo-uploader is actually listed as a dependency)
Adding the dependency here as well for consistency.
(The reason that it was not included previously I believe was to enable installing sim2sumo outside of Komodo without too much other stuff, but don't think that really makes anymore)
> chore: add sumo-uploader to dependency list

- .github/workflows/build_docs.yaml
- .github/workflows/run_tests.yaml
- .readthedocs.yml
- pyproject.toml
Closes #136 
`test_with_ert.py` is failing when using version `ert>=14.0.0` due to [this change](https://github.com/equinor/ert/pull/9860/files)
The introduction of `PyQt6` also requires `libegl1` to be installed.
For the existing tests to run, which we probably want, we need the test runner to have `libegl1` installed.
Closes #140 
Use `fmu-dataio` dev schema
> fix: install required dependency on test runner

- .github/workflows/run_tests.yaml
- tests/data/reek/realization-0/iter-0/share/results/tables/.2_r001_reek--rft.csv.yml
- tests/data/reek/realization-0/iter-0/share/results/tables/.2_r001_reek--wellconnstatus.csv.yml
- tests/data/reek/share/metadata/fmu_case.yml
Related to https://github.com/equinor/fmu-sumo/issues/382
Sends message to "Sumo alerts" Slack channel if tests run during **scheduled nightly run**.
Message includes link to the logs for the failing run.
Needs https://github.com/equinor/fmu-sumo-sim2sumo/pull/137 for tests to pass.
> feat: Add notify on Slack step to github workflow

- src/fmu/sumo/sim2sumo/common.py
Recreating [this PR](https://github.com/equinor/fmu-sumo-sim2sumo/pull/141).
> fix: make datatypes=all return list of submodules (as intended)

- pyproject.toml
`arrow` is not the correct dependency for handling arrow files, it handles date/time formatting https://snyk.io/advisor/python/arrow.
Fix to have the correct dependency on `pyarrow`
> fix: correct dependency on pyarrow

- tests/conftest.py
- tests/test_functions.py
- tests/test_w_drogon.py
Closes #172 
- Delete specific objects (the `delete /children` method has been removed https://github.com/equinor/sumo-core-nodejs/pull/723)
- Update `check_sumo` to use `/search` and do not search using wildcards
> fix: delete objects separately after test
